server {
    listen 80;
    server_name localhost;

    # Gzip Komprimierung aktivieren
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_types text/plain text/css save-data application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Wichtig für React Router:
        try_files $uri $uri/ /index.html;
    }

    # Cache-Control für Assets (Bilder, JS, CSS) -> macht die Seite beim 2. Besuch extrem schnell
    location /assets/ {
        root /usr/share/nginx/html;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}