services:
  # Nginx Proxy Manager - Der Türsteher
  nginx-proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: messerschmiede-nginx-proxy
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt

  # Dein Frontend (React/Vite)
  frontend:
    build: ./frontend
    container_name: messerschmiede-frontend
    restart: unless-stopped
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
      - /app/node_modules

  # Dein Backend (Node.js)
  backend:
    build: ./backend
    container_name: messerschmiede-backend
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://marcel:e`RqjC6W1(k1@db:5432/messerschmiede_db
      - JWT_SECRET=dein_super_geheimes_passwort_123
    volumes:
      - ./backend:/app
      - /app/node_modules
      # Hier den absoluten Pfad von 'pwd' oben einsetzen:
      - /home/marcel/websites/Messerschmiede-Schwaiger/backend/images:/app/images
    depends_on:
      - db

  # Die Datenbank (PostgreSQL)
  db:
    image: postgres:15
    container_name: messerschmiede-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=marcel
      - POSTGRES_PASSWORD=e`RqjC6W1(k1
      - POSTGRES_DB=messerschmiede_db
    volumes:
      - messer_daten:/var/lib/postgresql/data

volumes:
  messer_daten: